export const tokens = {
  success: [
    { name: "success/100", value: "#dcfce7", cssVar: "--success-100", mode: "Mode 1" },
    { name: "success/200", value: "#bbf7d0", cssVar: "--success-200", mode: "Mode 1" },
    { name: "success/300", value: "#86efac", cssVar: "--success-300", mode: "Mode 1" },
    { name: "success/400", value: "#4ade80", cssVar: "--success-400", mode: "Mode 1" },
    { name: "success/500", value: "#22c55e", cssVar: "--success-500", mode: "Mode 1" },
    { name: "success/600", value: "#16a34a", cssVar: "--success-600", mode: "Mode 1" },
  ],
  destructive: [
    { name: "destructive/100", value: "#fee2e2", cssVar: "--destructive-100", mode: "Mode 1" },
    { name: "destructive/200", value: "#fecaca", cssVar: "--destructive-200", mode: "Mode 1" },
    { name: "destructive/300", value: "#fca5a5", cssVar: "--destructive-300", mode: "Mode 1" },
    { name: "destructive/400", value: "#f87171", cssVar: "--destructive-400", mode: "Mode 1" },
    { name: "destructive/500", value: "#ef4444", cssVar: "--destructive-500", mode: "Mode 1" },
    { name: "destructive/600", value: "#dc2626", cssVar: "--destructive-600", mode: "Mode 1" },
  ],
  generic: [
    { name: "generic/white", value: "#ffffff", cssVar: "--generic-white", mode: "Mode 1" },
    { name: "generic/black", value: "#000000", cssVar: "--generic-black", mode: "Mode 1" },
    { name: "generic/background", value: "#ffffff", cssVar: "--generic-background", mode: "Mode 1" },
    { name: "generic/foreground", value: "#111827", cssVar: "--generic-foreground", mode: "Mode 1" },
  ],
  primary: [
    { name: "primary/100", value: "#dbeafe", cssVar: "--primary-100", mode: "Mode 1" },
    { name: "primary/200", value: "#bfdbfe", cssVar: "--primary-200", mode: "Mode 1" },
    { name: "primary/300", value: "#93c5fd", cssVar: "--primary-300", mode: "Mode 1" },
    { name: "primary/400", value: "#60a5fa", cssVar: "--primary-400", mode: "Mode 1" },
    { name: "primary/500", value: "#3b82f6", cssVar: "--primary-500", mode: "Mode 1" },
    { name: "primary/600", value: "#2563eb", cssVar: "--primary-600", mode: "Mode 1" },
  ],
  secondary: [
    { name: "secondary/100", value: "#f3e8ff", cssVar: "--secondary-100", mode: "Mode 1" },
    { name: "secondary/200", value: "#e9d5ff", cssVar: "--secondary-200", mode: "Mode 1" },
    { name: "secondary/300", value: "#d8b4fe", cssVar: "--secondary-300", mode: "Mode 1" },
    { name: "secondary/400", value: "#c084fc", cssVar: "--secondary-400", mode: "Mode 1" },
    { name: "secondary/500", value: "#a855f7", cssVar: "--secondary-500", mode: "Mode 1" },
    { name: "secondary/600", value: "#9333ea", cssVar: "--secondary-600", mode: "Mode 1" },
  ],
  warning: [
    { name: "warning/100", value: "#fef3c7", cssVar: "--warning-100", mode: "Mode 1" },
    { name: "warning/200", value: "#fde68a", cssVar: "--warning-200", mode: "Mode 1" },
    { name: "warning/300", value: "#fcd34d", cssVar: "--warning-300", mode: "Mode 1" },
    { name: "warning/400", value: "#fbbf24", cssVar: "--warning-400", mode: "Mode 1" },
    { name: "warning/500", value: "#f59e0b", cssVar: "--warning-500", mode: "Mode 1" },
    { name: "warning/600", value: "#d97706", cssVar: "--warning-600", mode: "Mode 1" },
  ],
  neutral: [
    { name: "neutral/100", value: "#f5f5f4", cssVar: "--neutral-100", mode: "Mode 1" },
    { name: "neutral/200", value: "#e7e5e4", cssVar: "--neutral-200", mode: "Mode 1" },
    { name: "neutral/300", value: "#d6d3d1", cssVar: "--neutral-300", mode: "Mode 1" },
    { name: "neutral/400", value: "#a8a29e", cssVar: "--neutral-400", mode: "Mode 1" },
    { name: "neutral/500", value: "#78716c", cssVar: "--neutral-500", mode: "Mode 1" },
    { name: "neutral/600", value: "#57534e", cssVar: "--neutral-600", mode: "Mode 1" },
  ],
  gray: [
    { name: "gray/100", value: "#f3f4f6", cssVar: "--gray-100", mode: "Mode 1" },
    { name: "gray/200", value: "#e5e7eb", cssVar: "--gray-200", mode: "Mode 1" },
    { name: "gray/300", value: "#d1d5db", cssVar: "--gray-300", mode: "Mode 1" },
    { name: "gray/400", value: "#9ca3af", cssVar: "--gray-400", mode: "Mode 1" },
    { name: "gray/500", value: "#6b7280", cssVar: "--gray-500", mode: "Mode 1" },
    { name: "gray/600", value: "#4b5563", cssVar: "--gray-600", mode: "Mode 1" },
  ],
  sidebar: [
    { name: "sidebar/background", value: "#030303", cssVar: "--sidebar-background", mode: "Mode 1" },
    { name: "sidebar/border-blue", value: "#1D8CFF", cssVar: "--sidebar-border-blue", mode: "Mode 1" },
    { name: "sidebar/border-dark", value: "#111827", cssVar: "--sidebar-border-dark", mode: "Mode 1" },
    { name: "sidebar/muted", value: "#8B949E", cssVar: "--sidebar-muted", mode: "Mode 1" },
    { name: "sidebar/purple", value: "#5B45F4", cssVar: "--sidebar-purple", mode: "Mode 1" },
    { name: "sidebar/logo-purple", value: "#6D4CFF", cssVar: "--sidebar-logo-purple", mode: "Mode 1" },
    { name: "sidebar/status-bg", value: "rgba(22, 163, 74, 0.08)", cssVar: "--sidebar-status-bg", mode: "Mode 1" },
  ],
};

export const tokenGroups = Object.entries(tokens).map(([title, groupTokens]) => ({
  title,
  tokens: groupTokens,
}));

export const appTheme = {
  colors: {
    pageBg: "#F7F8FC",
    appBg: "#F4F6FB",
    cardBg: "#FFFFFF",
    surface: "#F8FAFC",
    sectionBg: "#F3F4F6",
    text: "#0F172A",
    mutedText: "#64748B",
    subtleText: "#94A3B8",
    border: "#E2E8F0",
    borderSubtle: "#F1F5F9",
    borderMuted: "#E5E7EB",
    primary: "#6366F1",
    primaryStrong: "#5B45F4",
    primaryHover: "#4F46E5",
    primaryBg: "#EEF2FF",
    primaryTrack: "#C7D2FE",
    qualifiedBorder: "#C7D2FE",
    success: "#22C55E",
    successText: "#16A34A",
    successBg: "#DCFCE7",
    successSoft: "#ECFDF5",
    successBorder: "#A7F3D0",
    danger: "#EF4444",
    dangerBg: "#FEF2F2",
    dangerSoft: "#FEE2E2",
    dangerBorder: "#FECACA",
    warning: "#F59E0B",
    warningText: "#92400E",
    warningBg: "#FFFBEB",
    warningBorder: "#FDE68A",
    slate: "#334155",
    sidebar: "#0B1120",
    sidebarActive: "#1A2540",
    avatarBlue: "#4867FF",
    leadStrip: "#A9B5FF",
    leadBorder: "#BBD2FF",
    tagBorder: "#AFC2FF",
    backgroundPrimary: "#FFFFFF",
    backgroundSecondary: "#F7F8FC",
    backgroundMuted: "#F8FAFC",
    card: "#FFFFFF",
    muted: "#64748B",
    textPrimary: "#0F172A",
    textSecondary: "#64748B",
    textMuted: "#94A3B8",
  },
  font: {
    family: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif",
    size: {
      tiny: 10,
      caption: 11,
      xs: 12,
      bodySmall: 13,
      sm: 13,
      body: 14,
      cardTitle: 15,
      sectionTitle: 16,
      pageTitle: 22,
      metric: 26,
      dashboardValue: 30,
    },
    weight: {
      medium: 500,
      semibold: 600,
      bold: 700,
      extraBold: 800,
    },
  },
  spacing: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    page: 24,
    pageCompactY: 20,
    card: 16,
    cardCompact: 14,
    gap: 10,
    sectionGap: 16,
    headerGap: 12,
  },
  radius: {
    sm: 8,
    md: 10,
    lg: 12,
    xl: 14,
    card: 14,
    cardLg: 16,
    section: 18,
    pill: 999,
    circle: "50%",
  },
  border: {
    subtle: "1px solid #E2E8F0",
    soft: "1px solid #F1F5F9",
    muted: "1px solid #E5E7EB",
    none: "none",
  },
  shadow: {
    none: "none",
    xs: "0 1px 2px rgba(15, 23, 42, 0.04)",
    sm: "0 1px 3px rgba(15, 23, 42, 0.06)",
    soft: "0 10px 30px rgba(15, 23, 42, 0.05)",
  },
  layout: {
    pageMaxWidth: 1600,
    dashboardSectionHeight: "auto",
    sidebarWidth: 280,
    modalWidth: 420,
    successModalWidth: 380,
  },
};
