export const updateCellValue = async () => ({});
export const addColumnValue = async () => ({});
export const addRowValue = async () => ({ data: { row_id: Date.now().toString() } });
export const deleteRowValue = async () => ({});
export const deleteRowsValue = async () => ({});
export const duplicateRowValue = async () => ({});
export const updateColumnValue = async () => ({});
export const createBlankTable = async () => ({ data: { id: Date.now().toString(), name: "New Grid" } });
export const importTable = async () => ({});
export const renameTable = async () => ({});
export const deleteTable = async () => ({});
export const duplicateTable = async () => ({});
export const deleteColumnValue = async () => ({});
export const duplicateColumnValue = async () => ({});
export const addUser = async () => ({});
export const deleteUser = async () => ({});
export const updateUser = async () => ({});
export const appendTable = async () => ({});